#
# Copyright 2026 The xLLM Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/jd-opensource/xllm/blob/main/LICENSE
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ==============================================================================

function(hipify_sources_target OUT_SRCS OUT_TARGET NAME ORIG_SRCS)
  set(options)
  set(oneValueArgs)
  set(multiValueArgs EXTRA_HIPIFY_FILES)
  cmake_parse_arguments(
    ARG
    "${options}"
    "${oneValueArgs}"
    "${multiValueArgs}"
    ${ARGN}
  )

  set(SRCS ${ORIG_SRCS})
  set(CXX_SRCS ${ORIG_SRCS})

  # Files that need hipification, usually .cu/.cuh/.h/.hpp.
  list(FILTER SRCS EXCLUDE REGEX "\\.(cc|cpp|cxx|hip)$")

  # C++/HIP sources are passed through unchanged.
  list(FILTER CXX_SRCS INCLUDE REGEX "\\.(cc|cpp|cxx|hip)$")

  set(KERNELS_SRC_ROOT "${CMAKE_SOURCE_DIR}/xllm/core/kernels")

  # When the current directory is <build>/xllm/core/kernels/dcu,
  # the parent directory is <build>/xllm/core/kernels.
  get_filename_component(
    KERNELS_BUILD_ROOT
    "${CMAKE_CURRENT_BINARY_DIR}"
    DIRECTORY
  )

  set(HIPIFY_INPUTS)
  set(GENERATED_DCU_SRCS)
  set(GENERATED_DCU_BYPRODUCTS)

  foreach(SRC ${SRCS})
    if(IS_ABSOLUTE "${SRC}")
      set(SRC_ABS "${SRC}")
    else()
      set(SRC_ABS "${CMAKE_SOURCE_DIR}/${SRC}")
    endif()

    if(NOT EXISTS "${SRC_ABS}")
      message(FATAL_ERROR "hipify input source does not exist: ${SRC_ABS}")
    endif()

    file(RELATIVE_PATH REL_PATH "${KERNELS_SRC_ROOT}" "${SRC_ABS}")

    if(REL_PATH MATCHES "^\\.\\.")
      message(FATAL_ERROR
        "Source ${SRC_ABS} is not under kernels root ${KERNELS_SRC_ROOT}")
    endif()

    set(DCU_REL "${REL_PATH}")

    # cuda/foo.cu -> dcu/foo.hip
    string(REGEX REPLACE "\\.cu$" ".hip" DCU_REL "${DCU_REL}")

    # cuda/foo.cuh -> dcu/foo.cuh
    # cuda/foo.h   -> dcu/foo.h
    # cuda/foo.hpp -> dcu/foo.hpp
    string(REGEX REPLACE "^cuda/" "dcu/" DCU_REL "${DCU_REL}")
    string(REPLACE "/cuda/" "/dcu/" DCU_REL "${DCU_REL}")

    set(GENERATED_FILE "${KERNELS_BUILD_ROOT}/${DCU_REL}")

    list(APPEND HIPIFY_INPUTS "${SRC_ABS}")
    list(APPEND GENERATED_DCU_BYPRODUCTS "${GENERATED_FILE}")

    if(GENERATED_FILE MATCHES "\\.(hip|cpp|cc|cxx)$")
      list(APPEND GENERATED_DCU_SRCS "${GENERATED_FILE}")
    endif()
  endforeach()

  foreach(HDR ${ARG_EXTRA_HIPIFY_FILES})
    if(IS_ABSOLUTE "${HDR}")
      set(HDR_ABS "${HDR}")
    else()
      set(HDR_ABS "${CMAKE_SOURCE_DIR}/${HDR}")
    endif()

    if(NOT EXISTS "${HDR_ABS}")
      message(FATAL_ERROR "extra hipify file does not exist: ${HDR_ABS}")
    endif()

    file(RELATIVE_PATH REL_PATH "${KERNELS_SRC_ROOT}" "${HDR_ABS}")

    if(REL_PATH MATCHES "^\\.\\.")
      message(FATAL_ERROR
        "Extra hipify file ${HDR_ABS} is not under kernels root "
        "${KERNELS_SRC_ROOT}")
    endif()

    set(DCU_REL "${REL_PATH}")
    string(REGEX REPLACE "^cuda/" "dcu/" DCU_REL "${DCU_REL}")
    string(REPLACE "/cuda/" "/dcu/" DCU_REL "${DCU_REL}")

    list(APPEND HIPIFY_INPUTS "${HDR_ABS}")
    list(APPEND GENERATED_DCU_BYPRODUCTS "${KERNELS_BUILD_ROOT}/${DCU_REL}")
  endforeach()

  list(REMOVE_DUPLICATES HIPIFY_INPUTS)
  list(REMOVE_DUPLICATES GENERATED_DCU_SRCS)
  list(REMOVE_DUPLICATES GENERATED_DCU_BYPRODUCTS)

  set(HIPIFY_TARGET "${NAME}_hipify")
  set(HIPIFY_STAMP "${CMAKE_CURRENT_BINARY_DIR}/${NAME}_hipify.stamp")

  add_custom_command(
    OUTPUT
      "${HIPIFY_STAMP}"
    COMMAND
      "${Python_EXECUTABLE}"
        "${CMAKE_SOURCE_DIR}/cmake/hipify.py"
        -p "${CMAKE_SOURCE_DIR}/xllm/core/kernels"
        -o "${CMAKE_BINARY_DIR}/xllm/core/kernels"
        ${HIPIFY_INPUTS}
    COMMAND
      "${CMAKE_COMMAND}" -E touch "${HIPIFY_STAMP}"
    DEPENDS
      "${CMAKE_SOURCE_DIR}/cmake/hipify.py"
      ${HIPIFY_INPUTS}
    BYPRODUCTS
      ${GENERATED_DCU_BYPRODUCTS}
    COMMENT
      "Hipifying CUDA kernels for DCU: ${NAME}"
    VERBATIM
  )

  add_custom_target(${HIPIFY_TARGET}
    DEPENDS "${HIPIFY_STAMP}"
  )

  # Tell CMake these files are generated by the hipify target.
  foreach(GEN_SRC ${GENERATED_DCU_SRCS})
    set_source_files_properties("${GEN_SRC}" PROPERTIES GENERATED TRUE)
  endforeach()

  list(APPEND GENERATED_DCU_SRCS ${CXX_SRCS})
  list(REMOVE_DUPLICATES GENERATED_DCU_SRCS)

  set(${OUT_SRCS} ${GENERATED_DCU_SRCS} PARENT_SCOPE)
  set(${OUT_TARGET} ${HIPIFY_TARGET} PARENT_SCOPE)
endfunction()
